### PR TITLE
* refactored line

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by toineheuvelmans** [comment]
Hi @adamnemecek, thanks for your pr. Can you clarify the added value of your changes? Is it merely stylistic or is there a performance benefit in these changes (if so, can you point me to any resource that describes why)?

**Comment by adamnemecek** [comment]
it's more idiomatic

**Comment by toineheuvelmans** [comment]
I googled a bit on this, and cannot find any definitive answer as to what is more idiomatic. Even Apple seems to be using both approaches:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Patterns.html#//apple_ref/doc/uid/TP40014097-CH36-ID520

I'm tended to not merge this p.r., but if you can provide some reliable resource to support your claim that this is more idiomatic, I will certainly reconsider.

**Comment by adamnemecek** [comment]
It's shorter without reducing clarity. Ergo, it's more idiomatic.

**Pull request merged**
